### PR TITLE
What's the branch to which Pull Requests are sent?

### PR DESCRIPTION
**Pull request by kmizu**
* I want to remove some unused/old files
* Then,  I want to send PRs to the appropriate branch.
* However, I don't know which branch is appropriate!

### CODE REVIEW

**Comment by kmizu** [comment]
* If it possible, it should be reported as an issue.  However, issues are not seen, I created the issue as the pull request.

**Comment by seratch** [comment]
Although I think using pull requests for such a purpose is not preferred (scalate has ML and IRC), I can understand your argument well. 

To: @rossabaker and all the maintainers:
As we know, this issue tracker is not actively maintained. https://www.assembla.com/spaces/scalate/support/tickets

How about opening GitHub issues for this project (I don't have a permission to do so)? That may galvanize pull requests from not only current maintainers but all the Scala community. I'm grateful for your consideration.

**Comment by lloydmeta** [comment]
> How about opening GitHub issues for this project

:+1:  to this idea. It actually took me longer to figure out how to use Assembla than to figure out the source of NPEs and fix the problem for #64. Using Github Issues be a big step forward in my opinion.

**Comment by kmizu** [comment]
> How about opening GitHub issues for this project (I don't have a permission to do so)?

:+1:

**Comment by rossabaker** [comment]
I have reopened GitHub issues, now that I can.  Let's deprecate Assembla.

I find it most convenient to target scala_2.10 in pull requests, and then merge that branch into scala_2.11.  Anything that compiles in 2.10 without deprecation warnings should compile against 2.11, whereas the reverse is not necessarily true.

Another good technique some projects use is to isolate the code that varies between Scala versions into a src/main/scala_2.10 and src/main/scala_2.11, which are conditionally added by the SBT build.  I like this approach even better when the difference is small, but this would be a hassle with the existing Maven build.  If someone likes this better and wants to see what it would look like for Scalate, that would be okay with me.

**Comment by seratch** [comment]
@kmizu 
As @rossabaker mentioned [here](https://github.com/scalate/scalate/pull/65#issuecomment-77869562), Scalate project's default branch is currently `scala_2.10`. Would you please create another pull request against `scala_2.10`? Let me close this pull request without merging. We appreciate your understanding.

**Comment by kmizu** [comment]
@seratch OK. I closed

**Pull request closed without merging**
