### PR TITLE
2.9 guava

### PR DESCRIPTION
**Pull request by dnatic09**
This change removes multiple synchronization blocks that hamper performance.

Switched caching mechanism to use Google Guava cache.  This can be reimplemented as a new class that overrides the base implementation of TemplateEngine with the new caching schema.

### CODE REVIEW

**Comment by rossabaker** [comment]
This looks like a win, but I'd like to hear what some others think:

1. It breaks binany compatibility of the TemplateEngine interface.  Minor version bump?
2. Is everyone comfortable taking on guava a core dependency?

**Comment by dnatic09** [comment]
As mentioned above, I am more than happy to reimplement as a class that extends TemplateEngine that overrides necessary methods. Taking on an additional dependency is up to you project owners. You usually need FindBugs dependency when using Google Guava with Scala.

**Comment by rossabaker** [comment]
My main worry is that the extra constructor parameter on the template engine is going to break other projects that integrate with Scalate.  It's source compatible, but would require those projects to recompile against the new version.  Keeping the existing signature as a secondary constructor would alleviate this concern without resorting to a subclass.

Guava has a pretty solid record of binary compatibility.  I'm :+1: to the dependency.

@seratch, do you want to fit this into the pending release, or release yours now and do another as soon as this is resolved?

**Comment by seratch** [comment]
@rossabaker 

>release yours now and do another as soon as this is resolved

I hope we go with this plan. And I agree that the bin compatibility issue should be fixed if we will merge this PR in minor releases.

**Comment by seratch** [comment]
@rossabaker 
In this context, version 1.7.0 was published against only Scala 2.11 and 2.10. http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.scalatra.scalate%22

This pull request is against Scala 2.9 branch. I think we should no longer maintain this branch.

**Comment by dnatic09** [comment]
The concerns of binary compatibility are valid.   I will implement it again as an overriding class tonight.  If you do not want to maintain the branch, that is fine too.

**Comment by rossabaker** [comment]
I agree that we should not maintain 2.9.  I would still like the caching improvements.  We can merge the pull request into scala_2.10 (as discussed in #66) when it's done.

**Comment by shveik** [comment]
As a side note?l, have you guys looked at caffeine cache? We ran some benchmarks that I can dig up to compare the too, I think caffeine was more performant

**Pull request closed without merging**
