### PR TITLE
Scala 2.12.0-RC2 Support

### PR DESCRIPTION
**Pull request by seratch**
This pull request enables to build also in Scala 2.12.0-RC2.

**Important notice:**
This implementation has one limitation that is going to drop OSGi support from Scalate. The reasons to decide it are:

- The OSGi support heavily depends on Scala compiler's internal APIs fully changed in 2.12
 - I've tried for a while to keep it but it's not smooth at least for me
- IMO, the OSGi support is not so important for most users in 2016
 - At least, I can't motivate me to maintain the OSGi support anymore
 - If someone needs OSGi support again, he/she can send a pull request to enable it

After waiting comments on this for a day, I'll merge this pull request. I need to work on other improvements (i.e. upgrading dependencies) before releasing new versions. I appreciate your understanding of our situation.

### CODE REVIEW

**Comment by arashi01** [comment]
@seratch OSGi support is still very important for our use, and likely to be even more important for us in the future.

Do you mind letting us know what needs to be done to maintain OSGi compatibility for Scala 2.12?

**Comment by seratch** [comment]
@arashi01 If we can migrate `OsgiScalaCompiler` with Scala 2.12 compiler, there is no problem to keep OSGi support. But Scala compiler 2.12 has many breaking changes that affect the class. Do you have time to work on it?

**Comment by arashi01** [comment]
@seratch I'm definitely willing to take a look at it. I'll do so later, and update.

In the meantime, I'm OK with proceeding as planned, (as long as re-adding OSGi support in future via pull-request is an acceptable option to all).

**Comment by seratch** [comment]
@arashi01 OK, Thanks. In that case, I'll revert the changes on build settings (sbt plugin removal) and just disable OsgiScalaCompiler implementation so far.

**Comment by arashi01** [comment]
Sounds good. Thanks!

**Pull request merged**
