### PR TITLE
Switching to sbt (thanks to @arashi01, #69) with Travis builds

### PR DESCRIPTION
**Pull request by seratch**
This pull request enables to check https://github.com/scalate/scalate/pull/69 works on Travis. Let me merge this after a successful build.

### CODE REVIEW

**Comment by seratch** [comment]
Ah, since I'm not an admin member of this organization, I couldn't activate Travis for this project.. Can anyone activate?

https://travis-ci.org/profile/scalate

screen shot 2016-10-30 at 23 32 41

**Comment by rkrzewski** [comment]
I've enabled teavis.ci for scalate/scalate

**Comment by seratch** [comment]
@rkrzewski Thanks! The first ever build just started 😃

**Comment by seratch** [comment]
Looks fine. We have master branch but basically the latest release is came from this branch. I'd like to merge changes that exist only in master branch. And then, rename this branch as new `master` branch.

**Pull request merged**
