### PR TITLE
Add thread-safe RW access of Introspector cache (2.10)

### PR DESCRIPTION
**Pull request by lloydmeta**
`WeakHashMap` is *not* thread safe and will (has, in my experience) cause odd problems like `null`s being returned due to different threads accessing/modifying it at the same time if not synchronised.

Same as #63 but for 2.10

### CODE REVIEW

**Comment by rossabaker** [comment]
Looks good, thanks!

**Comment by seratch** [comment]
@rossabaker Do you have any plans to release next version soon? If Scalate team needs some more help from community, I'm willing to do trivial things (e.g. updating website, sonatype release and so on) instead of you.

**Comment by rossabaker** [comment]
I'm not actively working on Scalate right now, but I'm happy to help look at pull requests.

It would be nice to do a patch release now that we have a bug fix. Release and website help on that would be great.

**Comment by seratch** [comment]
Thank you for your quick reply. I'm not a maintainer of this project and doesn't have the permission to publish libs on sonatype. I'd like to make a pull request to `gh-pages` branch to update the website immediately after 1.7.1 release.

**Comment by seratch** [comment]
To: @rossabaker and all the maintainers
Is there any update? Our team (includes @lloydmeta) is waiting for this fix two weeks. 

If there is no active maintainer who works on patch releasing now, I'm willing to do that (not only website but also sonatype release stuff). Please add my sonatype account (seratch) like this. https://issues.sonatype.org/browse/OSSRH-13198

**Comment by rossabaker** [comment]
Thanks for the reminder. I fell behind the past couple weeks. I will work
on this as soon as I get home tonight.

**Comment by seratch** [comment]
Thanks in advance.

**Comment by lloydmeta** [comment]
Thanks guys :+1:

**Comment by rossabaker** [comment]
I've opened https://issues.sonatype.org/browse/OSSRH-14328 for the publish rights.

**Comment by seratch** [comment]
@rossabaker Thanks a lot :+1: I'll work on the Scalatra release stuff too.

**Comment by rossabaker** [comment]
I'm running into this.  I have to go to bed.  If someone wants to pick up after me, it's release_2.10-1.7.1 and release_2.11-1.7.1.  Otherwise, I'll try again tomorrow.

```
typeId	sources-staging
failureMessage	Missing: no sources jar found in folder '/org/scalatra/scalate/scalate-test_2.10/1.7.1'
failureMessage	Missing: no sources jar found in folder '/org/scalatra/scalate/scalate-jrebel_2.11/1.7.1'
failureMessage	Missing: no sources jar found in folder '/org/scalatra/scalate/scalate-test_2.11/1.7.1'
failureMessage	Missing: no sources jar found in folder '/org/scalatra/scalate/sbt-scalate-plugin_2.11/1.7.1'
failureMessage	Missing: no sources jar found in folder '/org/scalatra/scalate/sbt-scalate-plugin_2.10/1.7.1'
failureMessage	Missing: no sources jar found in folder '/org/scalatra/scalate/scalate-jrebel_2.10/1.7.1'
```

**Comment by rossabaker** [comment]
I finally got the build to work.  I had to run it like this: `mvn -Pdownload package source:jar gpg:sign deploy:deploy`.  1.7.1 is on the way to Maven Central.

I really hope #68 can get done before we ever release again. :)

**Comment by seratch** [comment]
@rossabaker Thanks a lot!

>I really hope #68 can get done before we ever release again. :)

Fully agreed. :+1:

**Comment by lloydmeta** [comment]
Cool, thanks a lot :+1:

**Pull request merged**
