### PR TITLE
Recursively loads the classpath of the parent class loader

### PR DESCRIPTION
**Pull request by giiita**
- https://github.com/scalate/scalate/issues/405

When running ssp compilation from the sbt console, a compatibility error occurs when writing a process in the template that may refer to a symbol in scala-reflect

This is because the configuration of the classloader has changed due to the sbt update, and may occur in the future depending on the sbt version.

(This may also occur in applications with a special class loader configuration, such as Play framework.)

This problem can be avoided by manually adding the classpath, but it is difficult for users to be aware of the dependency on scala-reflect.
```scala
engine.classpath = engine.classpath + ":" + "/Users/giiita/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.6/scala-reflect-2.13.6.jar"
engine.combinedClassPath = true
```

### CODE REVIEW

**Comment by magnolia-k** [comment]
Can I add a test for this code?

**Comment by giiita** [comment]
@magnolia-k 
Added a test.

**Comment by magnolia-k** [comment]
@giiita 

Please check the error in the test by GitHub Action.

**Comment by giiita** [comment]
@magnolia-k 
It was a Runtime environment dependent failure. Please check the fix.
https://github.com/scalate/scalate/pull/414/commits/e56ac237a9fab63cdabc60dceba7a7bcd7189019

**Comment by magnolia-k** [comment]
@giiita 
Java8's test are failure

**Comment by giiita** [comment]
@magnolia-k
Fixed. local has confirmed passage with java8 and 11.

**Comment by magnolia-k** [comment]
merged!
thanks!

**Comment by giiita** [comment]
@magnolia-k 
Is there a plan to release this fix?

**Pull request merged**
